USE [WebStor];
GO

CREATE SCHEMA ANDREEV;
GO

CREATE TABLE ANDREEV.DATATYPES (
    ID BIGINT, 
    AGE TINYINT 
);
GO

INSERT INTO ANDREEV.DATATYPES (ID, AGE)
VALUES (10000, 34);

INSERT INTO ANDREEV.DATATYPES (ID, AGE)
VALUES (10001, 32);

INSERT INTO ANDREEV.DATATYPES (ID, AGE)
VALUES (10002, 32);

INSERT INTO ANDREEV.DATATYPES (ID, AGE)
VALUES (10003, 35);

INSERT INTO ANDREEV.DATATYPES (ID, AGE)
VALUES (19700101, 35);
SELECT *
FROM ANDREEV.DATATYPES;
GO