USE [WebStor];

GO
CREATE SCHEMA IOVOVA;   
GO







CREATE TABLE IOVOVA.DATATYPES (
       ID  BIGINT, 
	   AGE TINYINT 
);


INSERT INTO IOVOVA.DATATYPES(ID, AGE)
VALUES(10000, 34);

INSERT INTO IOVOVA.DATATYPES(ID, AGE)
VALUES(10001, 32);

-- Implicit data type conversion
INSERT INTO IOVOVA.DATATYPES(ID, AGE)
VALUES('10002', 32);

-- Implicit data type conversion
INSERT INTO IOVOVA.DATATYPES(ID, AGE)
VALUES('10003', '35');

-- Implicit data type conversion
INSERT INTO IOVOVA.DATATYPES(ID, AGE)
VALUES('19700101', '35');

-- Implicit data type conversion IS NOT WORKING!
INSERT INTO IOVOVA.DATATYPES(ID, AGE) 
VALUES(10004, DATEDIFF(YEAR, '1970-01-01', GETDATE()));

SELECT * 
  FROM IOVOVA.DATATYPES;
