USE [WebStor];

GO
CREATE SCHEMA KLYMENKO;   
GO

CREATE TABLE KLYMENKO.DATATYPES (
       ID  BIGINT, 
	   AGE TINYINT 
);

INSERT INTO KLYMENKO.DATATYPES(ID, AGE)
VALUES(10000, 34);

INSERT INTO KLYMENKO.DATATYPES(ID, AGE)
VALUES(10001, 32);

-- Implicit data type conversion
INSERT INTO KLYMENKO.DATATYPES(ID, AGE)
VALUES('10002', 32);

-- Implicit data type conversion
INSERT INTO KLYMENKO.DATATYPES(ID, AGE)
VALUES('10003', '35');

-- Implicit data type conversion
INSERT INTO KLYMENKO.DATATYPES(ID, AGE)
VALUES('19700101', '35');

-- Implicit data type conversion IS NOT WORKING!
INSERT INTO KLYMENKO.DATATYPES(ID, AGE) 
VALUES(10004, DATEDIFF(YEAR, '1970-01-01', GETDATE()));





SELECT * 
  FROM KLYMENKO.DATATYPES;