USE [WebStor];

GO
CREATE SCHEMA Solomyana;
GO

CREATE TABLE Solomyana.DATATYPES (
       ID  BIGINT, 
	   AGE TINYINT 
);

INSERT INTO Solomyana.DATATYPES(ID, AGE)
VALUES(10000, 34);

INSERT INTO Solomyana.DATATYPES(ID, AGE)
VALUES(10001, 32);


INSERT INTO Solomyana.DATATYPES(ID, AGE)
VALUES('10002', 32);


INSERT INTO Solomyana.DATATYPES(ID, AGE)
VALUES('10003', '35');


INSERT INTO Solomyana.DATATYPES(ID, AGE)
VALUES('19700101', '35');


INSERT INTO Solomyana.DATATYPES(ID, AGE)
VALUES('1970-01-01', '35');

SELECT * 
  FROM Solomyana.DATATYPES;
